"""Gmail daily report sender."""
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime


def send_daily_report(
    sender: str,
    app_password: str,
    recipient: str,
    cea_result: dict,
    ccer_result: dict,
    cea_summary: dict,
    ccer_summary: dict,
    alerts: list[str] | None = None,
):
    """Send daily trading data report via Gmail."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    subject = f"[China ETS] Daily Report - {datetime.now().strftime('%Y-%m-%d')}"

    if alerts:
        subject = f"[ALERT] {subject}"

    html = f"""<html><body>
<h2>China ETS Daily Report</h2>
<p><strong>Generated</strong>: {now}</p>

<h3>CEA (Carbon Emission Allowance)</h3>
<table border="1" cellpadding="5" cellspacing="0">
<tr><td>New Records</td><td>{cea_result.get('new_records', 0)}</td></tr>
<tr><td>Latest Date</td><td>{cea_result.get('latest_date', 'N/A')}</td></tr>
<tr><td>Latest Price</td><td>{cea_summary.get('latest_closing_price', 0):.2f} CNY/ton</td></tr>
<tr><td>Total Trading Days</td><td>{cea_summary.get('total_trading_days', 0)}</td></tr>
</table>

<h3>CCER (Certified Emission Reduction)</h3>
<table border="1" cellpadding="5" cellspacing="0">
<tr><td>New Records</td><td>{ccer_result.get('new_records', 0)}</td></tr>
<tr><td>Latest Date</td><td>{ccer_result.get('latest_date', 'N/A')}</td></tr>
<tr><td>Latest Avg Price</td><td>{ccer_summary.get('latest_avg_price', 0):.2f} CNY/ton</td></tr>
<tr><td>Total Trading Days</td><td>{ccer_summary.get('total_trading_days', 0)}</td></tr>
</table>
"""

    if alerts:
        html += "<h3 style='color:red'>Alerts</h3><ul>"
        for alert in alerts:
            html += f"<li>{alert}</li>"
        html += "</ul>"

    html += """<hr><p><em>Generated by china-ets-mcp | JIN-Z-pop and his merry AI brothers</em></p>
</body></html>"""

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = sender
    msg["To"] = recipient
    msg.attach(MIMEText(html, "html"))

    with smtplib.SMTP("smtp.gmail.com", 587) as server:
        server.starttls()
        server.login(sender, app_password)
        server.sendmail(sender, recipient, msg.as_string())

    return {"status": "sent", "recipient": recipient, "subject": subject}
